runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /image 
  static_dir: image
  


- url: /css
  static_dir: css
  
- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  